# docker-compose.yml

version: '3.8'

services:
  # Application Service (PHP-FPM)
  # app:
  #   image: almerwalker/magix-app:latest
  #   container_name: laravel_app
  #   restart: unless-stopped
  #   working_dir: /var/www
  #   environment:
  #     DB_CONNECTION: ${DB_CONNECTION}
  #     DB_DATABASE: ${DB_DATABASE}
  #     DB_USERNAME: ${DB_USERNAME}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_PORT: 3306
  #     DB_HOST: ${DB_HOST}
  #   volumes:
  #     - app-code:/var/www
  #   networks:
  #     - laravel

  # # Web Server Service (Nginx)
  # webserver:
  #   image: nginx:alpine
  #   container_name: laravel_webserver
  #   restart: unless-stopped
  #   ports:
  #     - "80:80" # Access the app via http://localhost:8080
  #     - "443:443"
  #   volumes:
  #     - app-code:/var/www:ro
  #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./docker/nginx/ssl:/etc/nginx/ssl
  #   networks:
  #     - laravel
  #   depends_on:
  #     - app

  # Database Service (MySQL)
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
      - ./.env:/root/.env:ro
    ports:
      - "3306:3306" # Connect from host using port 33061
    networks:
      - laravel

# Define the network
networks:
  laravel:
    driver: bridge

# Define the named volume for persistent DB data
volumes:
  dbdata:
    driver: local
  # app-code:
  #   driver: local